# Generated by Django 5.2.4 on 2025-12-21 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=50, verbose_name='')),
                ('memberMail', models.EmailField(max_length=254, verbose_name='')),
                ('memberContact', models.CharField(max_length=50, verbose_name='')),
                ('memberPassword', models.CharField(max_length=50, verbose_name='')),
                ('memberAddress', models.CharField(max_length=50, verbose_name='')),
                ('memberImage', models.FileField(upload_to=None, verbose_name='')),
                ('memberType', models.CharField(choices=[('OWNER', 'OWNER'), ('RENTER', 'RENTER')], default='OWNER', max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location_type', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=10)),
                ('floor', models.IntegerField()),
                ('flat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='issues/')),
                ('status', models.CharField(default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrowdSolver.categoryname')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrowdSolver.member')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='CrowdSolver.member')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('Description', models.TextField(verbose_name='Description')),
                ('approve_count', models.IntegerField(default=0)),
                ('reject_count', models.IntegerField(default=0)),
                ('Issue_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrowdSolver.issue', verbose_name='')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrowdSolver.member')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField()),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrowdSolver.member')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrowdSolver.solutions')),
            ],
            options={
                'unique_together': {('solution', 'member')},
            },
        ),
    ]
