# Generated by Django 4.1.3 on 2026-04-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdSolver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberImage',
            field=models.FileField(blank=True, null=True, upload_to='members/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberMail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberPassword',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
