# Generated by Django 5.2.4 on 2025-12-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdSolver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberContact',
            field=models.CharField(max_length=10, verbose_name=''),
        ),
    ]
