# Generated by Django 5.2.4 on 2025-12-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdSolver', '0002_alter_member_membercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
