# Generated by Django 5.2.4 on 2025-12-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdSolver', '0003_solutions_is_approved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solutions',
            unique_together={('submitted_by', 'Issue_details')},
        ),
    ]
