# Generated by Django 5.2.4 on 2025-12-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdSolver', '0004_alter_solutions_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solutions',
            unique_together=set(),
        ),
    ]
