# Generated by Django 6.0.4 on 2026-04-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdSolver', '0002_alter_member_memberimage_alter_member_membermail_and_more'),
        ('CrowdSolver', '0005_alter_solutions_unique_together'),
    ]

    operations = [
    ]
