# Generated by Django 6.0.4 on 2026-04-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdSolver', '0006_merge_20260425_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberImage',
            field=models.FileField(blank=True, null=True, upload_to=None, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberMail',
            field=models.EmailField(max_length=254, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberPassword',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
    ]
